### PR TITLE
Adding better UI to highlight delete

### PR DESCRIPTION
**Pull request by kyleburgess2025**
The goal of this PR is to switch the UI for deleting highlights from a traditional HTML popup alert to a modified version of the Delete Note modal.

## UI Changes
Before:
image

After:
image

## Small State Management Changes
Instead of storing just the number of highlights, I have switched back to storing the highlight objects themselves. I have also slightly modified the `note-delete.tsx` component to work with both highlights and notes.

Known Issues:
Sometimes, after adding a highlight, it will appear correctly until refreshing. Upon refreshing, the highlight disappears and the following error appears in the console:
image
I have been unable to find a way to reproduce this reliably. **This bug is also occurring in the main branch.** Please let me know if you have an idea of why this might be happening.

### CODE REVIEW

**Comment by theannachen** [comment]
Quick confirmation regarding the actual changes: 
They're currently being all done in the BLLE repository. To make these changes apply for other textbooks, the same changes will also have to be applied to those as well.

Long term, would it be a better solution to factor the components, such as highlighting, which appear in all textbooks out into the packages, allowing for the change to apply to all deployments? If so, do you think we should keep this PR open until that change has been implemented?

**Comment by kyleburgess2025** [comment]
@theannachen Agreed - the current changes are just in the BLLE folder, but we might want to move the highlight/note components to the root folder. @qiushiyan thoughts? Let me know if I should continue with this - if so, I can include it in this PR.

**Comment by qiushiyan** [comment]
Looks good. @kyleburgess2025 Can you work on move this to `packages/core`? I think we don't need to change cornell or the law one at this point, but will use this for future textbooks.

**Comment by kyleburgess2025** [comment]
> Looks good. @kyleburgess2025 Can you work on moving this to `packages/core`? I think we don't need to change cornell or the law one at this point, but will use this for future textbooks.

This might be difficult, a lot of stuff would have to be moved out of the textbook-specific folders to get this to work. I'll get started on it but it might have to be the first step toward moving all of the non-textbook-specific components out of textbook folders.

**Comment by qiushiyan** [comment]
reworked in #21

**Pull request closed without merging**
